# Generated by Django 5.1 on 2024-08-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_content_html_alter_post_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content_html",
        ),
    ]
